// The models and the path helpers of this application, as types.
//
// Generated by henri -- `henri types`, every development boot and every
// hot reload write it -- from `app/models` and `config/routes.js`. It is
// gitignored and safe to delete: nothing reads it at runtime.
//
// 3 models, 16 path helpers.
//
// A record carries exactly the columns of its model file plus the ones
// henri adds, so a wrong column name is an error. A model carries what
// the adapter of its store answers: closed on a drizzle store, where
// the model class belongs to henri, and open on the two where it
// belongs to an ORM at whatever version this application installed.
//
// An editor reads it through `jsconfig.json`. Errors are opt-in: add
// `// @ts-check` at the top of a file, or turn `checkJs` on for the
// whole application. See https://usehenri.io/reference/types/

// What the interfaces below are built on: the declarations
// `@usehenri/core` ships by hand, aliased here because an interface
// extends a name and not an import type.
type HenriModelQuery<T> = import('@usehenri/core').ModelQuery<T>;
type HenriDrizzleModelStatics<T> = import('@usehenri/core').DrizzleModelStatics<T>;
type HenriDrizzleRecord = import('@usehenri/core').DrizzleRecord;

// --- Note --------------------------------------------------------------

/** A Note record, as the default store hands it back. */
interface NoteRecord extends HenriDrizzleRecord {
  body: string | null;
}

/** The `Note` model: a global in every file of this application. */
interface NoteModel extends HenriDrizzleModelStatics<NoteRecord> {}

declare const Note: NoteModel;

// --- Task --------------------------------------------------------------

/** A Task record, as the default store hands it back. */
interface TaskRecord extends HenriDrizzleRecord {
  body: string | null;
  createdAt: Date;
  /** The soft delete stamp (`options.paranoid`). */
  deletedAt: Date | null;
  dueOn: Date | null;
  estimate: string | null;
  /** The public identifier: the only one that leaves the server. `findById()` takes it. Unique. */
  externalId: string;
  /** A declared reference to User: the column holds that row's key, and what leaves the server is its externalId. */
  ownerId: string | null;
  payload: any;
  points: number | null;
  /** Unique. */
  reference: string | null;
  /** Personal, and never in an answer henri builds -- it is on the record all the same. */
  secret: string | null;
  /** The name every url of this record carries, written by henri (`options.slug`). Unique. */
  slug: string;
  status: 'draft' | 'in_review' | 'live';
  title: string;
  updatedAt: Date;
  urgent: boolean;
  /** `status === "draft"` */
  isDraft(): boolean;
  /** `status === "in_review"` */
  isInReview(): boolean;
  /** `status === "live"` */
  isLive(): boolean;
  /** Brings a soft-deleted record back (`options.paranoid`). */
  restore(): Promise<any>;
}

/** The `Task` model: a global in every file of this application. */
interface TaskModel extends HenriDrizzleModelStatics<TaskRecord> {
  /** The record of a slug (`options.slug`), or null. */
  findBySlug(slug: string, ...args: any[]): HenriModelQuery<TaskRecord | null>;
  /** The values every enum column of this model accepts. */
  enums: {
    status: readonly ('draft' | 'in_review' | 'live')[];
  };
  /** `{ status: "draft" }`, intersected with what it is given. */
  draft(where?: Record<string, any>): Record<string, any>;
  /** `{ status: "in_review" }`, intersected with what it is given. */
  inReview(where?: Record<string, any>): Record<string, any>;
  /** `{ status: "live" }`, intersected with what it is given. */
  live(where?: Record<string, any>): Record<string, any>;
}

declare const Task: TaskModel;

// --- User --------------------------------------------------------------

/** A User record, as the default store hands it back. */
interface UserRecord extends HenriDrizzleRecord {
  confirmedAt: Date | null;
  createdAt: Date;
  /** Unique. */
  email: string;
  /** The public identifier: the only one that leaves the server. `findById()` takes it. Unique. */
  externalId: string;
  /** Personal: exported, erased and masked in the logs. */
  name: string | null;
  /** Hashed, and not selected by default: a record read the usual way does not carry it. */
  password?: string;
  passwordChangedAt: Date | null;
  /** Encrypted at rest; the model hands back the string. */
  phone: string | null;
  /** Stripped from mass assignment: `setRoles()` or `{ unsafe: true }` writes it. */
  roles: any;
  updatedAt: Date;
  /** Does this user hold every one of these roles? */
  hasRole(roles?: string | string[]): Promise<boolean>;
  /** The one write that may set `roles`. */
  setRoles(roles: string | string[]): Promise<any>;
}

/** The `User` model: a global in every file of this application. */
interface UserModel extends HenriDrizzleModelStatics<UserRecord> {
  /** The one write that may set `roles`. */
  setRoles(id: any, roles: string | string[]): Promise<UserRecord | null>;
}

declare const User: UserModel;

// --- the path helpers -------------------------------------------------

/**
 * Every path helper `config/routes.js` expands to. The keys are what
 * matters: they are the union `pathFor()` and `getRoute()` take, so a
 * helper that does not exist is a compile error rather than a link that
 * goes nowhere.
 */
interface HenriPaths {
  /** `POST /admin/tasks` -> admin/tasks#create */
  'create_admin/tasks_path': true;
  /** `DELETE /admin/tasks/:id` -> admin/tasks#destroy */
  'destroy_admin/tasks_path': true;
  /** `GET /admin/tasks` -> admin/tasks#index */
  'index_admin/tasks_path': true;
  /** `PUT /admin/tasks/:id` -> admin/tasks#update */
  'update_admin/tasks_path': true;
  /** `GET /about` -> main#about */
  about_main_path: true;
  /** `POST /tasks/:id/archive` -> tasks#archive */
  archive_tasks_path: true;
  /** `POST /tasks` -> tasks#create */
  create_tasks_path: true;
  /** `DELETE /tasks/:id` -> tasks#destroy */
  destroy_tasks_path: true;
  /** `GET /tasks/:id/edit` -> tasks#edit */
  edit_tasks_path: true;
  /** `GET /` -> main#home */
  home_main_path: true;
  /** `GET /notes` -> notes#index */
  index_notes_path: true;
  /** `GET /tasks` -> tasks#index */
  index_tasks_path: true;
  /** `GET /tasks/new` -> tasks#new */
  new_tasks_path: true;
  /** `GET /notes/:id` -> notes#show */
  show_notes_path: true;
  /** `GET /tasks/:id` -> tasks#show */
  show_tasks_path: true;
  /** `PUT /tasks/:id` -> tasks#update */
  update_tasks_path: true;
}

// henri:types 2 app=44f1cc051143
