const Sequelize = require('sequelize');

module.exports = {
  // Mongoose specific
  String: Sequelize.STRING,
  Number: Sequelize.NUMBER,
  Boolean: Sequelize.BOOLEAN,
  DocumentArray: Sequelize.ARRAY,
  Embedded: Sequelize.STRING,
  Array: Sequelize.ARRAY,
  Buffer: Sequelize.BLOB,
  Date: Sequelize.DATE,
  ObjectId: Sequelize.STRING,
  Mixed: Sequelize.JSON,
  Decimal128: Sequelize.BIGINT,
  Object: Sequelize.JSON,
  Bool: Sequelize.BOOLEAN,

  // Sequelize specific
  STRING: Sequelize.STRING,
  CHAR: Sequelize.CHAR,
  TEXT: Sequelize.TEXT,
  TINYINT: Sequelize.TINYINT,
  SMALLINT: Sequelize.SMALLINT,
  MEDIUMINT: Sequelize.MEDIUMINT,
  INTEGER: Sequelize.INTEGER,
  BIGINT: Sequelize.BIGINT,
  FLOAT: Sequelize.FLOAT,
  DOUBLE: Sequelize.DOUBLE,
  DECIMAL: Sequelize.DECIMAL,
  REAL: Sequelize.REAL,
  BOOLEAN: Sequelize.BOOLEAN,
  BLOB: Sequelize.BLOB,
  ENUM: Sequelize.ENUM,
  DATE: Sequelize.DATE,
  DATEONLY: Sequelize.DATEONLY,
  TIME: Sequelize.TIME,
  NOW: Sequelize.NOW,
  UUID: Sequelize.UUID,
  UUIDV1: Sequelize.UUIDV1,
  UUIDV4: Sequelize.UUIDV4,
  HSTORE: Sequelize.HSTORE,
  JSON: Sequelize.JSON,
  JSONB: Sequelize.JSONB,
  ARRAY: Sequelize.ARRAY,
  RANGE: Sequelize.RANGE,
  GEOMETRY: Sequelize.GEOMETRY,
  GEOGRAPHY: Sequelize.GEOGRAPHY,
  VIRTUAL: Sequelize.VIRTUAL,
};
