/**
 * Files the Inertia engine reads from app/views. The engine creates them on
 * first boot when the application ships none of the alternatives (`henri new
 * --renderer inertia` ships them too).
 */
const VIEW_FILES = [
  {
    // The html shell: <!--head--> and <!--body--> receive the rendered page
    alternatives: [],
    content: `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!--head-->
    <title>henri</title>
  </head>
  <body>
    <!--body-->
  </body>
</html>
`,
    name: 'index.html',
  },
  {
    // The browser entry
    alternatives: ['main.js', 'main.tsx', 'main.ts'],
    content: `// Generated by henri: the browser entry of the Inertia view engine.
// Pages live under ./pages and are resolved from the route a controller
// passes to res.render(): '/tasks/index' -> ./pages/tasks/index.jsx
// Global styles: \`import './styles/index.scss';\`
import { createInertiaApp } from '@inertiajs/react';
import { resolvePage } from '@usehenri/inertia';

const pages = import.meta.glob('./pages/**/*.jsx');

createInertiaApp({
  progress: { color: '#0000ff' },
  resolve: (name) => resolvePage(pages, name),
});
`,
    name: 'main.jsx',
  },
  {
    // The server-side rendering entry
    alternatives: ['ssr.js', 'ssr.tsx', 'ssr.ts'],
    content: `// Generated by henri: the server-side rendering entry of the Inertia engine.
// \`render(page)\` resolves to { head, body }, injected in index.html.
import { createInertiaApp } from '@inertiajs/react';
import { resolvePage } from '@usehenri/inertia';
import { renderToString } from 'react-dom/server';

const pages = import.meta.glob('./pages/**/*.jsx');

export function render(page) {
  return createInertiaApp({
    page,
    render: renderToString,
    resolve: (name) => resolvePage(pages, name),
    setup: ({ App, props }) => <App {...props} />,
  });
}
`,
    name: 'ssr.jsx',
  },
  {
    // Vite reads its configuration from disk
    alternatives: [
      'vite.config.js',
      'vite.config.ts',
      'vite.config.mts',
      'vite.config.cjs',
    ],
    content: `// Generated by henri: the Vite configuration of the Inertia view engine.
// It wires the React plugin, the components/, styles/, helpers/ and assets/
// aliases and the client + server builds. Extend it with Vite's mergeConfig:
//
//   import { mergeConfig } from 'vite';
//   export default mergeConfig(henriViteConfig({ views: import.meta.dirname }), {});
import { henriViteConfig } from '@usehenri/inertia/vite';

export default henriViteConfig({ views: import.meta.dirname });
`,
    name: 'vite.config.mjs',
  },
];

module.exports = { VIEW_FILES };
