const path = require('path');
const fs = require('fs');
const { spawnSync } = require('child_process');
const next = require('next');
const debug = require('debug')('henri:react');
const { loadUserHooks } = require('./hooks');

/**
 * Files next.js reads from app/views. They are created when the application
 * ships none of the alternatives (`henri new` ships them too).
 */
const VIEW_FILES = [
  {
    // `next build` reads its configuration from disk
    alternatives: [
      'next.config.js',
      'next.config.cjs',
      'next.config.mjs',
      'next.config.ts',
    ],
    content: `// Generated by henri. It lets \`next build\` find the henri view configuration.
// Extend it through config/next.js (or config/webpack.js) instead of editing it.
module.exports = require('@usehenri/react/engine/conf');
`,
    name: 'next.config.js',
  },
  {
    // Import aliases: 'components/x', 'styles/x', 'helpers/x', 'assets/x'
    alternatives: ['jsconfig.json', 'tsconfig.json'],
    content: `${JSON.stringify(
      { compilerOptions: { baseUrl: '.' } },
      null,
      2
    )}\n`,
    name: 'jsconfig.json',
  },
];

/**
 * React (next.js) view engine
 *
 * @class ReactEngine
 */
class ReactEngine {
  /**
   * Creates an instance of ReactEngine.
   *
   * @param {Henri} thisHenri The current henri instance
   * @memberof ReactEngine
   */
  constructor(thisHenri) {
    this.instance = null;
    this.handle = null;
    this.upgrade = null;
    this.henri = thisHenri;
    this.dir = path.resolve(thisHenri.cwd(), './app/views');
    this.renderer = thisHenri.config.get('renderer').toLowerCase();

    this.conf = thisHenri.isTest ? {} : require('./conf');
    this.bundler = loadUserHooks(thisHenri.cwd()).webpack
      ? 'webpack'
      : 'turbopack';

    this.init = this.init.bind(this);
    this.build = this.build.bind(this);
    this.prepare = this.prepare.bind(this);
    this.fallback = this.fallback.bind(this);
    this.render = this.render.bind(this);
    this.close = this.close.bind(this);
  }

  /**
   * Checks the application dependencies
   *
   * @async
   * @returns {Promise<boolean>} success
   * @memberof ReactEngine
   */
  async init() {
    const {
      pen,
      utils: { checkPackages },
    } = this.henri;

    if (this.renderer !== 'react') {
      pen.warn(
        'view',
        `renderer '${this.renderer}' is no longer supported; using react`
      );
    }

    await checkPackages(['next', 'react', 'react-dom']);

    try {
      this.resolve('sass');
    } catch (error) {
      pen.warn('view', "'sass' is not installed: .scss files will not compile");
    }

    if (!this.henri.isTest) {
      this.ensureNextConfig();
    }

    return true;
  }

  /**
   * Resolve a module from the application directory
   *
   * @param {string} request module name
   * @returns {string} resolved path
   * @memberof ReactEngine
   */
  resolve(request) {
    return require.resolve(request, { paths: [this.henri.cwd()] });
  }

  /**
   * Create the files next.js needs in app/views (next.config.js and
   * jsconfig.json) when the application does not ship them.
   *
   * @returns {string[]} the files that were created
   * @memberof ReactEngine
   */
  ensureNextConfig() {
    const created = [];

    for (const file of VIEW_FILES) {
      const exists = file.alternatives.some((name) =>
        fs.existsSync(path.join(this.dir, name))
      );

      if (!exists) {
        try {
          fs.writeFileSync(path.join(this.dir, file.name), file.content);
          this.henri.pen.info('view', `created app/views/${file.name}`);
          created.push(file.name);
        } catch (error) {
          this.henri.pen.warn(
            'view',
            `unable to create app/views/${file.name}`,
            error.message
          );
        }
      }
    }

    return created;
  }

  /**
   * Production build (runs `next build` on app/views)
   *
   * @async
   * @throws when the build fails
   * @returns {Promise<void>} nothing
   * @memberof ReactEngine
   */
  async build() {
    const { pen } = this.henri;

    pen.info('view', `building next.js pages for production (${this.bundler})`);

    this.ensureNextConfig();

    const result = spawnSync(
      process.execPath,
      [
        require.resolve('next/dist/bin/next'),
        'build',
        this.dir,
        `--${this.bundler}`,
      ],
      {
        cwd: this.henri.cwd(),
        env: Object.assign({}, process.env, { NODE_ENV: 'production' }),
        stdio: 'inherit',
      }
    );

    if (result.status !== 0) {
      pen.error('view', 'unable to generate a production build');
      throw new Error(`next build exited with status ${result.status}`);
    }
  }

  /**
   * Called after init to prepare the server
   *
   * @async
   * @returns {Promise<boolean>} success
   * @memberof ReactEngine
   */
  async prepare() {
    const { pen } = this.henri;
    const buildId = path.join(this.dir, '.next', 'BUILD_ID');

    if (this.henri.isProduction) {
      if (!fs.existsSync(buildId) || process.env.FORCE_BUILD === 'true') {
        await this.build();

        if (process.env.CMD_BUILD === 'true') {
          pen.info(
            'react',
            `build ${fs.readFileSync(buildId, 'utf8')} successful`,
            'exiting'
          );
          process.exit(0);
        }
      } else {
        pen.info('view', 'reusing production build');
      }
    }

    const versions = {
      next: require(
        path.resolve(require.resolve('next'), '../../../package.json')
      ).version,

      react: require(this.resolve('react/package.json')).version,
    };

    pen.info(
      'view',
      'starting next.js instance...',
      `next.js = ${versions.next}`,
      `react = ${versions.react}`,
      `bundler = ${this.bundler}`
    );

    const options = {
      conf: this.conf,
      customServer: true,
      dev: !this.henri.isProduction,
      dir: this.dir,
    };

    options[this.bundler] = true;

    this.instance = next(options);

    await this.instance.prepare();

    this.handle = this.instance.getRequestHandler();
    this.upgrade =
      typeof this.instance.getUpgradeHandler === 'function'
        ? this.instance.getUpgradeHandler()
        : null;

    this.attachUpgrade();

    return true;
  }

  /**
   * Forward next.js websocket upgrades (dev hot reloading) to next.js
   *
   * @returns {boolean} attached?
   * @memberof ReactEngine
   */
  attachUpgrade() {
    const server = this.henri.server && this.henri.server.httpServer;

    if (!server || !this.upgrade || this.upgradeAttached) {
      return false;
    }

    server.on('upgrade', (req, socket, head) => {
      if ((req.url || '').startsWith('/_next/')) {
        debug('forwarding upgrade for %s to next.js', req.url);
        this.upgrade(req, socket, head);
      }
    });

    this.upgradeAttached = true;

    return true;
  }

  /**
   * Add catchall route to render directly from the folder
   *
   * @param {Express.Router} router A router to register the catchall
   * @returns {void}
   * @memberof ReactEngine
   */
  fallback(router) {
    const handle = this.handle || this.instance.getRequestHandler();

    // `use` without a path works the same on express 4 and 5
    router.use((req, res, done) => {
      if (req.method !== 'GET' && req.method !== 'HEAD') {
        return done();
      }

      return handle(req, res);
    });
  }

  /**
   * Used by res.render
   *
   * The view options (data, paths, user, ...) are attached to the request as
   * `req._henri`, where withHenri's getInitialProps picks them up; next.js
   * then renders the page matching `route` with the original query string.
   *
   * @param {Express.Request} req Request
   * @param {Express.Response} res Response
   * @param {String} route A string matching the location from ./app/views/pages
   * @param {Object} opts Data or any other options going to the view
   * @returns {Promise<void>} An express response
   * @memberof ReactEngine
   */
  render(req, res, route, opts = {}) {
    const handle = this.handle || this.instance.getRequestHandler();
    const { search } = new URL(req.url || '/', 'http://henri.local');

    req._henri = Object.assign({}, req._henri, opts);

    return handle(req, res, {
      pathname: route === '/index' ? '/' : route,
      search,
    });
  }

  /**
   * Stops the next.js instance
   *
   * @async
   * @returns {Promise<boolean>} success
   * @memberof ReactEngine
   */
  async close() {
    if (this.instance && typeof this.instance.close === 'function') {
      await this.instance.close();
    }

    return true;
  }
}

module.exports = ReactEngine;
