CREATE TYPE "public"."events_state" AS ENUM('draft', 'open', 'closed', 'announced');
--> statement-breakpoint
CREATE TYPE "public"."proposals_format" AS ENUM('talk', 'workshop', 'lightning');
--> statement-breakpoint
CREATE TYPE "public"."proposals_level" AS ENUM('beginner', 'intermediate', 'advanced');
--> statement-breakpoint
CREATE TYPE "public"."proposals_state" AS ENUM('draft', 'submitted', 'accepted', 'rejected');
--> statement-breakpoint
CREATE TABLE "events" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"city" varchar(255),
	"closes_at" timestamp with time zone,
	"name" varchar(255) NOT NULL,
	"opens_at" timestamp with time zone,
	"slug" varchar(255) NOT NULL,
	"state" "events_state" DEFAULT 'draft',
	"summary" text,
	"year" integer NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	CONSTRAINT "events_slug_unique" UNIQUE("slug")
);

--> statement-breakpoint
CREATE TABLE "proposals" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "proposals_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"abstract" text NOT NULL,
	"decided_at" timestamp with time zone,
	"event_id" integer NOT NULL,
	"format" "proposals_format" DEFAULT 'talk',
	"level" "proposals_level" DEFAULT 'intermediate',
	"speaker_id" integer NOT NULL,
	"track_id" integer,
	"state" "proposals_state" DEFAULT 'draft',
	"submitted_at" timestamp with time zone,
	"title" varchar(255) NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"deleted_at" timestamp with time zone
);

--> statement-breakpoint
CREATE TABLE "reviews" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "reviews_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"comment" text NOT NULL,
	"proposal_id" integer NOT NULL,
	"reviewer_id" integer NOT NULL,
	"score" integer NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);

--> statement-breakpoint
CREATE TABLE "tracks" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tracks_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"blurb" text,
	"event_id" integer NOT NULL,
	"name" varchar(255) NOT NULL,
	"slug" varchar(255) NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);

--> statement-breakpoint
CREATE TABLE "users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"bio" text,
	"company" varchar(255),
	"name" varchar(255) NOT NULL,
	"email" varchar(255) NOT NULL,
	"password" varchar(255) NOT NULL,
	"roles" jsonb,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	CONSTRAINT "users_email_unique" UNIQUE("email")
);

--> statement-breakpoint
CREATE TABLE "henri_sessions" (
	"expires_at" timestamp with time zone NOT NULL,
	"sess" jsonb NOT NULL,
	"sid" varchar(255) PRIMARY KEY NOT NULL
);

--> statement-breakpoint
ALTER TABLE "proposals" ADD CONSTRAINT "proposals_event_id_events_id_fk" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "proposals" ADD CONSTRAINT "proposals_speaker_id_users_id_fk" FOREIGN KEY ("speaker_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "proposals" ADD CONSTRAINT "proposals_track_id_tracks_id_fk" FOREIGN KEY ("track_id") REFERENCES "public"."tracks"("id") ON DELETE set null ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_proposal_id_proposals_id_fk" FOREIGN KEY ("proposal_id") REFERENCES "public"."proposals"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_reviewer_id_users_id_fk" FOREIGN KEY ("reviewer_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "tracks" ADD CONSTRAINT "tracks_event_id_events_id_fk" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
CREATE INDEX "proposals_event_id_idx" ON "proposals" USING btree ("event_id");
--> statement-breakpoint
CREATE INDEX "proposals_speaker_id_idx" ON "proposals" USING btree ("speaker_id");
--> statement-breakpoint
CREATE INDEX "proposals_track_id_idx" ON "proposals" USING btree ("track_id");
--> statement-breakpoint
CREATE INDEX "proposals_state_idx" ON "proposals" USING btree ("state");
--> statement-breakpoint
CREATE INDEX "proposals_deleted_at_idx" ON "proposals" USING btree ("deleted_at");
--> statement-breakpoint
CREATE INDEX "reviews_proposal_id_idx" ON "reviews" USING btree ("proposal_id");
--> statement-breakpoint
CREATE INDEX "reviews_reviewer_id_idx" ON "reviews" USING btree ("reviewer_id");
--> statement-breakpoint
CREATE INDEX "tracks_event_id_idx" ON "tracks" USING btree ("event_id");
--> statement-breakpoint
CREATE INDEX "tracks_slug_idx" ON "tracks" USING btree ("slug");
--> statement-breakpoint
CREATE INDEX "henri_sessions_expires_at_idx" ON "henri_sessions" USING btree ("expires_at");