/* eslint-disable sort-keys */

module.exports = {
  // Mongoose specific
  Array: 'json',
  Bool: 'boolean',
  Boolean: 'boolean',
  Buffer: 'string',
  Date: 'number',
  Decimal128: 'string',
  DocumentArray: 'json',
  Embedded: 'ref',
  Mixed: 'string',
  Number: 'number',
  Object: 'json',
  ObjectId: 'ref',
  String: 'string',

  // Sequelize specific
  STRING: 'string',
  CHAR: 'string',
  TEXT: 'string',
  TINYINT: 'number',
  SMALLINT: 'number',
  MEDIUMINT: 'number',
  INTEGER: 'number',
  BIGINT: 'number',
  NUMBER: 'number',
  FLOAT: 'number',
  DOUBLE: 'number',
  DECIMAL: 'number',
  REAL: 'number',
  BOOLEAN: 'boolean',
  BLOB: 'string',
  ENUM: 'json',
  DATE: 'number',
  DATEONLY: 'number',
  TIME: 'number',
  NOW: 'number',
  UUID: 'string',
  UUIDV1: 'string',
  UUIDV4: 'string',
  HSTORE: 'string',
  JSON: 'json',
  JSONB: 'json',
  ARRAY: 'json',
  RANGE: 'string',
  GEOMETRY: 'string',
  GEOGRAPHY: 'string',
  VIRTUAL: 'json',
};
