/**
 * Runs before `changeset publish` (`pnpm sync-readme`, part of
 * `pnpm changeset:publish`). Every public package gets what its npm page
 * needs and what is not committed (see .gitignore):
 *
 * - LICENSE: a copy of the root license
 * - README.md: packages/henri gets a copy of the root README; the others get
 *   a short generated one unless they have their own
 * - @usehenri/mcp also gets docs/: a copy of the documentation pages, which
 *   its `guide` tool serves to an agent with the versions installed next to
 *   them (src/docs.js reads the website directly inside the monorepo)
 */
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const packagesDir = path.join(root, 'packages');
const marker = '<!-- generated by scripts/prepublish.js -->';
const docsSource = path.join(root, 'website/src/content/docs');
const docsTarget = path.join(packagesDir, 'mcp', 'docs');

/**
 * README of a package that has none of its own
 *
 * @param {object} pkg the package.json
 * @param {string} dirName the directory under packages/
 * @returns {string} markdown
 */
const readme = (pkg, dirName) => `${marker}

# ${pkg.name}

${pkg.description.charAt(0).toUpperCase()}${pkg.description.slice(1)}.

Part of [henri](https://usehenri.io), the Rails-like React framework for
Node.js: [documentation](https://usehenri.io),
[source and issues](https://github.com/usehenri/henri),
[changelog](https://github.com/usehenri/henri/blob/master/packages/${dirName}/CHANGELOG.md).
`;

/**
 * Copy the documentation pages into @usehenri/mcp
 *
 * @returns {number} how many pages were copied
 */
const copyDocs = () => {
  fs.rmSync(docsTarget, { force: true, recursive: true });

  let copied = 0;
  const walk = (from, to) => {
    fs.mkdirSync(to, { recursive: true });

    for (const entry of fs.readdirSync(from, { withFileTypes: true })) {
      if (entry.name.startsWith('.')) {
        continue;
      }

      if (entry.isDirectory()) {
        walk(path.join(from, entry.name), path.join(to, entry.name));
      } else if (/\.mdx?$/.test(entry.name)) {
        fs.copyFileSync(path.join(from, entry.name), path.join(to, entry.name));
        copied++;
      }
    }
  };

  walk(docsSource, docsTarget);

  return copied;
};

for (const dirName of fs.readdirSync(packagesDir)) {
  const dir = path.join(packagesDir, dirName);
  const pkgFile = path.join(dir, 'package.json');

  if (!fs.existsSync(pkgFile)) {
    continue;
  }

  const pkg = JSON.parse(fs.readFileSync(pkgFile, 'utf8'));

  if (pkg.private) {
    continue;
  }

  fs.copyFileSync(path.join(root, 'LICENSE'), path.join(dir, 'LICENSE'));

  const target = path.join(dir, 'README.md');

  if (pkg.name === 'henri') {
    fs.copyFileSync(path.join(root, 'README.md'), target);
    console.log(`${pkg.name}: LICENSE and the root README.md copied`);
    continue;
  }

  const generated =
    !fs.existsSync(target) ||
    fs.readFileSync(target, 'utf8').startsWith(marker);

  if (generated) {
    fs.writeFileSync(target, readme(pkg, dirName));
  }

  console.log(
    `${pkg.name}: LICENSE copied, README.md ${generated ? 'generated' : 'kept'}`
  );

  if (pkg.name === '@usehenri/mcp') {
    console.log(`${pkg.name}: ${copyDocs()} documentation pages copied`);
  }
}
